[package]
name = "assignment"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
solana-sdk = "2.3.1"
tokio = { version = "1.37", features = ["full"] }
serde_json = "1.0"
serde = "1.0.219"
bs58 = "0.5.1"
spl-token = "8.0.0"
base64 = "0.22.1"
